config/routes.rb
Rails.application.routes.draw do
  
  #get 'users/index'
  #get 'users/new'
  #get 'users/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #root 'albums#index'
  root 'home#index'
  get 'home/index'

  #spotify authentication
  get '/auth/spotify/callback', to: 'users#spotify'
  

  resources :albums, except: [:update, :destroy, :create, :new, :edit] do
    member do
      get "like", to: "albums#vote"
    end
  end

  get '/search' => 'albums#search', :as => 'search_page'
  post '/search' => 'albums#create'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  #signing in
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  #post 'login', to: 'sessions#create', as: 'session_create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  

end

app/models/album.rb
class Album < ApplicationRecord
	acts_as_votable
	#does not allow saving of album name-artist combo twice
	validates :name, uniqueness: { scope: :artist, case_sensitive: false }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	acts_as_voter
	EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z/i
	
	validates :email, presence: true, uniqueness: true, format: EMAIL_REGEX
  	validates :username, presence: true, case_sensitive: false, uniqueness: true, length: { in: 3..20 }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	require 'rspotify'

	RSpotify.authenticate(ENV['SPOTIFY_KEY'], ENV['SPOTIFY_SECRET'])

	def index
		#load 100 albums, order by votes
		@albums = Album.limit(100).order(cached_votes_total: :desc)
	end

	def show
		@album = Album.find(params[:id])
	end

	def search
		#display alert if query is empty
		if params[:q].blank?  
    		redirect_to(root_path, alert: "No input!")  
  		else 
  			#save parameter as instance variable so i dont have to keep typing params[:album]
			@parameter = params[:q]
			#search spotifies Album API
			@albums = RSpotify::Album.search(@parameter)
			#need to add some caching here to reduce searches and attempts to make database entries
			#for every result add to db. db will ignore if the album exists
			@albums.each do |album|
				Album.create(name: album.name, 
							 artist: album.artists.first.name, 
							 image: album.images.first['url'], 
							 votes: 0,
							 album_type: album.album_type,
							 genres: album.genres,
							 release_date: album.release_date,
							 total_tracks: album.total_tracks)
			end
			#reset the albums variable to search the db with fresh queries
			@albums = nil
			#applies a case insensitive search on both artist and album name
			@albums = Album.where("lower(artist) LIKE lower(?)", "%" + @parameter + "%").or(Album.where("lower(name) LIKE lower(?)", "%" + @parameter + "%"))

		end
	end

	def create
		#currently not using the create method, but ill keep in for future reference
		@album = Album.new(album_params)
		if @album.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def vote

		#check if user logged in
		if logged_in?
			@album = Album.find(params[:id])
			@album.upvote_by current_user
			redirect_back(fallback_location: root_path)
		else
			redirect_back(fallback_location: root_path)
		end
		#get album by id
		#@album = Album.find(params[:id])
		#increment votes
		#@album.increment!(:votes)
		#redirect
		#redirect_back(fallback_location: root_path)
	end

	private
		#not using this anymore, but ill keep it handy
		private
		  def album_params
		    params.require(:album).permit(:name, :artist, :image, :votes, :album_type, :genres, :release_date, :total_tracks)
		  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :login!, :logged_in?, :logout!

	#sets the currently logged in user as a helper method
	def current_user
		#finds a user based on the user id saved in the session cookie
		@current_user ||= User.find(session[:user_id])
	end

	#login helper method
	def login!
		#sets session id as user found id
		session[:user_id] = @user.id
	end

	#clears the session
	def logout!
		session.clear
	end

	#checks to see if ia user is logged in
	def logged_in?
		#turns session id into a boolean value to be returned
		#first exclamation turns into a boolean value (which is the opposite)
		#second converts it to the actual boolean value
		!!session[:user_id]
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(username: params[:username])

		if @user && @user.authenticate(params[:password])
			login!
			redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		logout!
		redirect_to root_path
	end

	private
		def session_params
			params.require(:user).permit(:username, :email, :password)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
    @albums = @user.get_up_voted Album
  end

  def new
  	@user = User.new
  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		login!
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
  end

  private
  	def user_params
  		params.require(:user).permit(:email, :username, :password, :password_confirmation, :admin)
  	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<div class="page-title">
	<h1>Top Albums</h1>
</div>

<%= alert %>
<div class="albums-container">
<% @albums.each do |album| %>
	<div class="album-card" id="">

		<div class="album-image">
			<%= image_tag(album.image) %>

			<div class="album-card-info">
				<strong><%= album.name %></strong>
				<p><%= album.artist %></p>
			</div>
		</div>

		<div class="album-card-footer">
			<p>Score: <%= album.votes %></p>
			<%= link_to 'Vote', like_album_path(album) %>
		</div>
	</div>
<% end %>
</div>

app/views/albums/search.html.erb
<div class="page-title">
	<h1> Results for: <%= @parameter %></h1>
</div>


<div class="albums-container">
<% @albums.each do |album| %>
	<div class="album-card" id="">
		
		<%= link_to album_path(album) do %>
		<div class="album-image">
			<%= image_tag(album.image) %>

			<div class="album-card-info">
				<strong><%= album.name %></strong>
				<p><%= album.artist %></p>
			</div>
		</div>
		<% end %>

		<div class="album-card-footer">
			<p>Score: <%= album.cached_votes_total %></p>
			<% if logged_in? %>
				<%= link_to 'Vote', like_album_path(album) %>
			<% else %>
				<%= link_to 'Log In to Vote', login_path %>
			<% end %>
		</div>
	</div>
<% end %>
</div>

app/views/albums/show.html.erb
<div class="page-title">
	<h1><%= @album.name %></h1>
</div>

<div class="albums-container">
	<div class="album-card" id="">

		<div class="album-image">
			<%= image_tag(@album.image) %>

			<div class="album-card-info">
				<strong><%= @album.name %></strong>
				<p><%= @album.artist %></p>
			</div>
		</div>

		<div class="album-card-footer">
			<p>Score: <%= @album.cached_votes_total %></p>
			<% if logged_in? %>
				<%= link_to 'Vote', like_album_path(@album) %>
			<% else %>
				<%= link_to 'Log In to Vote', login_path %>
			<% end %>
		</div>
	</div>

	<div class="scroll">
	<p>
		<%= @album.name %><br><br>
		By <%= @album.artist %><br><br>
		Released on <br> <%= @album.release_date %><br><br>
		Total Tracks: <%= @album.total_tracks %><br>
	</p>
	</div>
</div>

app/views/home/index.html.erb
<style>


body {
	background: linear-gradient(318deg, #212121, #49FB35, #77ABB7, #212121);
	background-size: 1000% 1000%;
	animation: gradient 20s ease infinite;
}



</style>

<div class="page-title">
	<h1>Welcome to SpotVote</h1>
</div>


<div class="page-title">
	<h4>Discover new music.</h4><br>
</div>

<div class="page-title">
	<h4>Vote for your favorite albums.</h4><br>
</div>

<div class="page-title">
	<h4>Share with friends.</h4><br>
</div>

<% if false %>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to 'Sign in with Spotify', '/auth/spotify' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotVote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" href="https://i.scdn.co/image/ab67616d0000b2734cb9510779e85a83d3f22a9c">
  
  </head>

  <body>
    
  
      <nav>
        <div class="mobile-nav">
          <div class="logo">
            <h4 class="active"><%= link_to 'SpotVote', root_path %></h4>
          </div>
          <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
          </div>
        </div>

        <ul class="nav-links hide-mobile" id="myLinks">
          <li class="hide-desktop"><%= link_to 'Home', root_path %></li>

          <% if false %>
          <li><%= link_to 'Upload Fit', new_fit_path %></li>
          <li><%= link_to 'Vote', fits_vote_path, :method => :post %></li>
          <% end %>

          <li><%= link_to 'Top Albums', albums_path %></li>
          <li><%= link_to 'All Users', users_path %></li>
          <% if logged_in? %>
          <li><%= link_to current_user.username + ' Page', user_path(current_user) %></li>
          <% end %>
          
          <% if logged_in? %>
            <li><%= link_to 'Log Out', logout_path %></li>
          <% else %>
            <li><%= link_to 'Log In', login_path %></li>
            <li><%= link_to 'Sign Up', signup_path %></li>
          <% end %>

          <li class="nav-search">
            <%= form_with(url: "./search", local: true, method: "get", class: ".search") do %>
              <%= label_tag(:q, "Album Search:") %>
              <%= search_field_tag(:q) %>
              <%= button_tag("Search") %>
            <% end %>
          </li>
         

        </ul>


        <% if false %>
        <div class="burger">
          <div class="line1"></div>
          <div class="line2"></div>
          <div class="line3"></div>
        </div>
        <% end %>

      </nav>

    

    <div class="spacer"></div>

      <p class="alert"><% alert %></p>
      <%= yield %>

    

    <script>
      var navSlide = () => {
        const burger = document.querySelector('.burger');
        const nav = document.querySelector('.nav-links');

        burger.addEventListener('click', () => {
          nav.classList.toggle('nav-active');
        });
      }

      navSlide();
    </script>
    

  </body>

</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="page-title">
	<h1>All Users</h1>
</div>

<div class="container">
	<% @users.each do |user| %>
		<%= link_to user.username, user_path(user), class: "btn", style: "margin: 10px" %>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="page-title">
	<h1>Sign Up!</h1>
</div>

<div class="container" style="display: flex; justify-content: center">

<%= form_with(model: @user, local: true, class: "user") do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> you gotta fix some stuff:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email, style: "width: 100%" %>
  </div>

  <br>

  <div class="field">
    <%= form.label :username %><br>
    <%= form.text_field :username, style: "width: 100%" %>
  </div>

  <br>

  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password, style: "width: 100%" %>
  </div>

  <br>

  <div class="field">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation, style: "width: 100%" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit class: "btn", value: "Sign Up!", style: "width: 100%" %>
  </div>
  <br>
<% end %>
</div>

app/views/users/show.html.erb
<div class="page-title">
	<h1><%= @user.username %> Page</h1>
</div>
<br>
<h4>Liked Albums</h4>
<br>

<div class="albums-container">
<% @albums.each do |album| %>
	
	<div class="album-card" id="">
		<%= link_to album_path(album) do %>
		<div class="album-image">
			<%= image_tag(album.image) %>

			<div class="album-card-info">
				<strong><%= album.name %></strong>
				<p><%= album.artist %></p>
			</div>
		</div>
		<% end %>

		<div class="album-card-footer">
			<p>Score: <%= album.cached_votes_total %></p>
			<% if logged_in? %>
				<%= link_to 'Vote', like_album_path(album) %>
			<% else %>
				<%= link_to 'Log In to Vote', login_path %>
			<% end %>
		</div>
	</div>
	
<% end %>
</div>